---
title: "p8105_nr2774"
output: github_document
---

### Problem 1

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(viridis)
library(dplyr)
library(rvest)
library(purrr)
library(ggplot2)
library(patchwork)
library(broom.mixed)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
payroll_df = 
    read_csv("data/Citywide_Payroll_Data__Fiscal_Year_ (1).csv") |> 
    clean_names() |>
    filter(fiscal_year == "2022") |>
    select(-payroll_number, -agency_name, -agency_start_date, -title_description) |> 
    mutate(pay_basis = recode(pay_basis, "per Annum" = "Annually"),
           pay_basis = recode(pay_basis, "per Day" = "Daily"),
           pay_basis = recode(pay_basis, "per Hour" = "Hourly"),
           leave_status = leave_status_as_of_june_30) |>
    filter(work_location_borough != "NA",work_location_borough != "OTHER") |> select(-leave_status_as_of_june_30)
             
```

